# Generated by Django 2.0.5 on 2018-05-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='data',
            new_name='date',
        ),
    ]
